use crate::models::{CommandAction, CommandCategory};

pub struct CommandRegistry {
    commands: Vec<CommandAction>,
}

impl CommandRegistry {
    pub fn new() -> Self {
        Self {
            commands: core_commands(),
        }
    }

    pub fn commands(&self) -> &[CommandAction] {
        &self.commands
    }
}

fn core_commands() -> Vec<CommandAction> {
    vec![
        // === Data ===
        CommandAction {
            id: "data.format-json".into(),
            title: "Format JSON".into(),
            subtitle: "Pretty-print or minify JSON payloads locally.".into(),
            category: CommandCategory::Data,
            tags: vec!["json".into(), "formatter".into(), "payload".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "data.minify-json".into(),
            title: "Minify JSON".into(),
            subtitle: "Compress JSON payloads into a single line locally.".into(),
            category: CommandCategory::Data,
            tags: vec!["json".into(), "minify".into(), "payload".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 022: Schema Inter-Converter ===
        CommandAction {
            id: "data.schema-convert".into(),
            title: "Schema Convert".into(),
            subtitle: "Convert between JSON, YAML, TOML, XML, and CSV. Prefix with 'to: yaml'.".into(),
            category: CommandCategory::Data,
            tags: vec!["convert".into(), "yaml".into(), "toml".into(), "xml".into(), "csv".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 023: JSON Flatten / Unflatten ===
        CommandAction {
            id: "data.json-flatten".into(),
            title: "JSON Flatten".into(),
            subtitle: "Flatten nested JSON objects into dot-notation key=value paths.".into(),
            category: CommandCategory::Data,
            tags: vec!["flatten".into(), "normalize".into(), "paths".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "data.json-unflatten".into(),
            title: "JSON Unflatten".into(),
            subtitle: "Rebuild nested JSON from flat dot-notation key=value pairs.".into(),
            category: CommandCategory::Data,
            tags: vec!["unflatten".into(), "rebuild".into(), "paths".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 024: SQL Statement Beautifier ===
        CommandAction {
            id: "data.sql-beautify".into(),
            title: "SQL Beautify".into(),
            subtitle: "Format raw SQL queries with proper indentation and line breaks.".into(),
            category: CommandCategory::Data,
            tags: vec!["sql".into(), "format".into(), "beautify".into(), "query".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 025: String Escaper / Unescaper ===
        CommandAction {
            id: "data.escape".into(),
            title: "String Escape".into(),
            subtitle: "Escape text for JSON strings, HTML attributes, or terminal/shell.".into(),
            category: CommandCategory::Data,
            tags: vec!["escape".into(), "json".into(), "html".into(), "terminal".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "data.unescape".into(),
            title: "String Unescape".into(),
            subtitle: "Unescape JSON, HTML, or terminal-escaped text.".into(),
            category: CommandCategory::Data,
            tags: vec!["unescape".into(), "json".into(), "html".into(), "terminal".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 026: CSV/TSV Visual Matrix ===
        CommandAction {
            id: "data.csv-table".into(),
            title: "CSV Table".into(),
            subtitle: "Render CSV or TSV data as a formatted text table.".into(),
            category: CommandCategory::Data,
            tags: vec!["csv".into(), "tsv".into(), "table".into(), "grid".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 027: Type Definition Generator ===
        CommandAction {
            id: "data.gen-types".into(),
            title: "Generate Types".into(),
            subtitle: "Generate TypeScript, Go, or Rust types from JSON. Prefix with 'ts:', 'go:', or 'rust:'.".into(),
            category: CommandCategory::Data,
            tags: vec!["types".into(), "generate".into(), "typescript".into(), "go".into(), "rust".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 028: Structural Schema Differ ===
        CommandAction {
            id: "data.struct-diff".into(),
            title: "Struct Diff".into(),
            subtitle: "Compare two JSON payloads separated by '---' on its own line.".into(),
            category: CommandCategory::Data,
            tags: vec!["diff".into(), "compare".into(), "schema".into(), "changes".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 029: URL Query Parameter Deconstructor ===
        CommandAction {
            id: "data.url-parse".into(),
            title: "URL Parse".into(),
            subtitle: "Deconstruct URLs into scheme, host, path, and query parameters.".into(),
            category: CommandCategory::Data,
            tags: vec!["url".into(), "parse".into(), "query".into(), "parameters".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 030: JSONPath Evaluator ===
        CommandAction {
            id: "data.path-eval".into(),
            title: "Path Eval".into(),
            subtitle: "Evaluate JSONPath expressions against JSON documents.".into(),
            category: CommandCategory::Data,
            tags: vec!["jsonpath".into(), "path".into(), "query".into(), "evaluate".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 011: Zero-Latency Process Port Mapper ===
        CommandAction {
            id: "net.port-mapper".into(),
            title: "Port Mapper".into(),
            subtitle: "Real-time list of all active TCP/UDP listeners with PID and binary name.".into(),
            category: CommandCategory::Network,
            tags: vec!["ports".into(), "listeners".into(), "process".into(), "tcp".into(), "udp".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 012: Atomic Process Termination ===
        CommandAction {
            id: "net.kill-process".into(),
            title: "Kill Process".into(),
            subtitle: "Terminate a process by PID with graceful or forced kill.".into(),
            category: CommandCategory::Network,
            tags: vec!["kill".into(), "process".into(), "pid".into(), "terminate".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 013: Multiplexed Port Monitor ===
        CommandAction {
            id: "net.port-monitor".into(),
            title: "Port Monitor".into(),
            subtitle: "Check if a port is in use and identify the occupying process.".into(),
            category: CommandCategory::Network,
            tags: vec!["port".into(), "monitor".into(), "check".into(), "listen".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 014: Local DNS Host File Editor ===
        CommandAction {
            id: "net.hosts-edit".into(),
            title: "Hosts Editor".into(),
            subtitle: "View, add, remove, or toggle entries in the system hosts file.".into(),
            category: CommandCategory::Network,
            tags: vec!["hosts".into(), "dns".into(), "etc".into(), "loopback".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 015: Reverse Proxy Tunnel Configuration Manager ===
        CommandAction {
            id: "net.tunnel-mgr".into(),
            title: "Tunnel Manager".into(),
            subtitle: "Manage ngrok, localtunnel, and cloudflared tunnels.".into(),
            category: CommandCategory::Network,
            tags: vec!["tunnel".into(), "ngrok".into(), "proxy".into(), "reverse".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 016: Network Interception Curl Builder ===
        CommandAction {
            id: "net.curl-builder".into(),
            title: "Curl Builder".into(),
            subtitle: "Convert raw HTTP request logs into reproducible curl commands.".into(),
            category: CommandCategory::Network,
            tags: vec!["curl".into(), "http".into(), "request".into(), "convert".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 017a: ICMP Ping Analyzer ===
        CommandAction {
            id: "net.ping".into(),
            title: "Ping".into(),
            subtitle: "Send ICMP echo requests and analyze latency, loss, and statistics.".into(),
            category: CommandCategory::Network,
            tags: vec!["ping".into(), "icmp".into(), "latency".into(), "diagnostic".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 017b: Traceroute Analyzer ===
        CommandAction {
            id: "net.trace".into(),
            title: "Traceroute".into(),
            subtitle: "Visualize network hops to a target host via ICMP or UDP probes.".into(),
            category: CommandCategory::Network,
            tags: vec!["traceroute".into(), "trace".into(), "hops".into(), "route".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 018: Public/Private IP Discovery ===
        CommandAction {
            id: "net.ip-discover".into(),
            title: "IP Discovery".into(),
            subtitle: "Show local network config, public IP, subnet mask, gateway, and MAC addresses.".into(),
            category: CommandCategory::Network,
            tags: vec!["ip".into(), "network".into(), "config".into(), "gateway".into(), "subnet".into()],
            shortcut: None,
            accepts_input: false,
        },
        // === 019: Domain & SSL Expiry Validator ===
        CommandAction {
            id: "net.domain-check".into(),
            title: "Domain Check".into(),
            subtitle: "Resolve DNS records and validate SSL certificate trust chain and expiry.".into(),
            category: CommandCategory::Network,
            tags: vec!["domain".into(), "ssl".into(), "dns".into(), "certificate".into(), "expiry".into()],
            shortcut: None,
            accepts_input: true,
        },
        // === 020: Local Subnet Sweep Engine ===
        CommandAction {
            id: "net.subnet-sweep".into(),
            title: "Subnet Sweep".into(),
            subtitle: "Fast async IP scan to discover active devices on the local subnet.".into(),
            category: CommandCategory::Network,
            tags: vec!["subnet".into(), "scan".into(), "discovery".into(), "network".into()],
            shortcut: None,
            accepts_input: true,
        },
        // ============================================================
        // Features 031–040: Advanced Cryptography & Key Management
        // ============================================================
        CommandAction {
            id: "crypto.hash".into(),
            title: "Hash Compute".into(),
            subtitle: "Compute MD5, SHA-1, SHA-256, SHA-512, and CRC32 hashes.".into(),
            category: CommandCategory::Crypto,
            tags: vec!["hash".into(), "md5".into(), "sha".into(), "crc32".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "crypto.jwt".into(),
            title: "JWT Inspect".into(),
            subtitle: "Decode JWT tokens to inspect header, payload, and signature.".into(),
            category: CommandCategory::Crypto,
            tags: vec!["jwt".into(), "token".into(), "decode".into(), "inspect".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "crypto.cipher".into(),
            title: "Symmetric Cipher".into(),
            subtitle: "Encrypt/decrypt with AES-256-CBC or ChaCha20. Usage: encrypt:aes256:<keyhex>:<text>".into(),
            category: CommandCategory::Crypto,
            tags: vec!["aes".into(), "chacha".into(), "encrypt".into(), "decrypt".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "crypto.rsa-keygen".into(),
            title: "RSA Keygen".into(),
            subtitle: "Generate RSA public/private keypair (default 2048 bits).".into(),
            category: CommandCategory::Crypto,
            tags: vec!["rsa".into(), "keygen".into(), "public".into(), "private".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "crypto.base64".into(),
            title: "Base64 Convert".into(),
            subtitle: "Encode text to base64 or decode base64 with 'decode:' prefix.".into(),
            category: CommandCategory::Crypto,
            tags: vec!["base64".into(), "encode".into(), "decode".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "crypto.hash-bench".into(),
            title: "Hash Benchmark".into(),
            subtitle: "Hash passwords with bcrypt, argon2, or scrypt.".into(),
            category: CommandCategory::Crypto,
            tags: vec!["bcrypt".into(), "argon2".into(), "scrypt".into(), "password".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "crypto.html-decode".into(),
            title: "HTML Decode".into(),
            subtitle: "Decode HTML entities, hex escapes, and URL-encoded sequences.".into(),
            category: CommandCategory::Crypto,
            tags: vec!["html".into(), "decode".into(), "entities".into(), "hex".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "crypto.gen-token".into(),
            title: "Generate Token".into(),
            subtitle: "Generate UUIDs, hex tokens, passwords, or PINs.".into(),
            category: CommandCategory::Crypto,
            tags: vec!["token".into(), "uuid".into(), "password".into(), "generate".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "crypto.hmac".into(),
            title: "HMAC Compute".into(),
            subtitle: "Compute HMAC-SHA256/512 signatures. Key on first line, message on second.".into(),
            category: CommandCategory::Crypto,
            tags: vec!["hmac".into(), "sha256".into(), "sha512".into(), "signature".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "crypto.vault".into(),
            title: "Crypto Vault".into(),
            subtitle: "In-memory encrypted vault for staging secrets. Commands: set, get, delete, list, clear".into(),
            category: CommandCategory::Crypto,
            tags: vec!["vault".into(), "secret".into(), "key".into(), "storage".into()],
            shortcut: None,
            accepts_input: true,
        },
        // ============================================================
        // Features 041–050: Clipboard & Text Processing
        // ============================================================
        CommandAction {
            id: "clip.stack".into(),
            title: "Clipboard Stack".into(),
            subtitle: "Push, list, and retrieve clipboard history items.".into(),
            category: CommandCategory::Clipboard,
            tags: vec!["clipboard".into(), "history".into(), "stack".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "clip.classify".into(),
            title: "Classify Text".into(),
            subtitle: "Auto-detect semantic type of pasted content (JSON, SQL, URL, etc).".into(),
            category: CommandCategory::Clipboard,
            tags: vec!["classify".into(), "detect".into(), "semantic".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "clip.snippets".into(),
            title: "Snippet Board".into(),
            subtitle: "Store and retrieve sticky text snippets. Commands: add, get, del, list, clear".into(),
            category: CommandCategory::Clipboard,
            tags: vec!["snippet".into(), "sticky".into(), "board".into(), "template".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "clip.merge-split".into(),
            title: "Merge / Split".into(),
            subtitle: "Merge lines with separator or split text by separator.".into(),
            category: CommandCategory::Clipboard,
            tags: vec!["merge".into(), "split".into(), "join".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "clip.regex".into(),
            title: "Regex Transform".into(),
            subtitle: "Find-and-replace using regex patterns, or strip matches.".into(),
            category: CommandCategory::Clipboard,
            tags: vec!["regex".into(), "replace".into(), "strip".into(), "find".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "clip.case".into(),
            title: "Case Normalize".into(),
            subtitle: "Convert text between camelCase, snake_case, kebab-case, and more.".into(),
            category: CommandCategory::Clipboard,
            tags: vec!["case".into(), "transform".into(), "camel".into(), "snake".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "clip.diff".into(),
            title: "Clipboard Diff".into(),
            subtitle: "Compare two texts separated by '---' and show line differences.".into(),
            category: CommandCategory::Clipboard,
            tags: vec!["diff".into(), "compare".into(), "lines".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "clip.whitespace".into(),
            title: "Whitespace Sanitizer".into(),
            subtitle: "Minify, trim, or collapse whitespace in text blocks.".into(),
            category: CommandCategory::Clipboard,
            tags: vec!["whitespace".into(), "minify".into(), "trim".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "clip.redact".into(),
            title: "Redact Data".into(),
            subtitle: "Detect and redact API keys, passwords, emails, IPs, and credit cards.".into(),
            category: CommandCategory::Clipboard,
            tags: vec!["redact".into(), "security".into(), "privacy".into(), "filter".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "clip.queue".into(),
            title: "Clip Queue".into(),
            subtitle: "FIFO multi-item queue for form-filling. Commands: push, pop, list, clear".into(),
            category: CommandCategory::Clipboard,
            tags: vec!["queue".into(), "fifo".into(), "stack".into(), "form".into()],
            shortcut: None,
            accepts_input: true,
        },
        // ============================================================
        // Features 051-060: Code Snippet Vault & Shell Assistant
        // ============================================================
        CommandAction {
            id: "shell.cheatsheet".into(),
            title: "Shell Cheat Sheet".into(),
            subtitle: "Search common tar, find, sed, awk, and chmod patterns by task, flag, or command.".into(),
            category: CommandCategory::System,
            tags: vec![
                "shell".into(),
                "cli".into(),
                "tar".into(),
                "find".into(),
                "sed".into(),
                "awk".into(),
                "chmod".into(),
                "reference".into(),
            ],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "shell.git-wizard".into(),
            title: "Git Wizard".into(),
            subtitle: "Generate command blueprints for rebase, squash, reset, detached HEAD recovery, and more.".into(),
            category: CommandCategory::System,
            tags: vec!["git".into(), "rebase".into(), "squash".into(), "reset".into(), "history".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "shell.code-vault".into(),
            title: "Code Vault".into(),
            subtitle: "Store, search, and retrieve code snippets with language-tagged fenced output.".into(),
            category: CommandCategory::System,
            tags: vec!["snippet".into(), "vault".into(), "code".into(), "save".into(), "search".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "shell.history".into(),
            title: "Shell History".into(),
            subtitle: "Search local bash, zsh, ash, or PowerShell history files for reusable commands.".into(),
            category: CommandCategory::System,
            tags: vec!["history".into(), "bash".into(), "zsh".into(), "powershell".into(), "search".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "shell.alias".into(),
            title: "Alias Generator".into(),
            subtitle: "Turn long commands into alias blueprints for bash, zsh, fish, PowerShell, or cmd.".into(),
            category: CommandCategory::System,
            tags: vec!["alias".into(), "shell".into(), "powershell".into(), "bash".into(), "cmd".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "shell.path-translate".into(),
            title: "Path Translator".into(),
            subtitle: "Convert paths between Windows, POSIX-style, and WSL-friendly formats.".into(),
            category: CommandCategory::System,
            tags: vec!["path".into(), "windows".into(), "posix".into(), "wsl".into(), "convert".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "shell.cron".into(),
            title: "Cron Explain".into(),
            subtitle: "Translate cron expressions and shortcuts into readable schedules.".into(),
            category: CommandCategory::System,
            tags: vec!["cron".into(), "schedule".into(), "crontab".into(), "time".into(), "parser".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "shell.compose".into(),
            title: "Compose Generator".into(),
            subtitle: "Generate Docker Compose YAML from compact service blocks.".into(),
            category: CommandCategory::System,
            tags: vec!["docker".into(), "compose".into(), "yaml".into(), "services".into(), "containers".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "shell.ansi-strip".into(),
            title: "ANSI Strip".into(),
            subtitle: "Remove terminal color and cursor-control escape codes from logs and command output.".into(),
            category: CommandCategory::System,
            tags: vec!["ansi".into(), "terminal".into(), "logs".into(), "escape".into(), "clean".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "shell.exit-code".into(),
            title: "Exit Code Reference".into(),
            subtitle: "Explain common Unix and Windows exit codes like 127, 130, 137, and 9009.".into(),
            category: CommandCategory::System,
            tags: vec!["exit code".into(), "status".into(), "unix".into(), "windows".into(), "diagnostic".into()],
            shortcut: None,
            accepts_input: true,
        },
        // ============================================================
        // Features 061-070: File System & Environment Organizer
        // ============================================================
        CommandAction {
            id: "fs.env-audit".into(),
            title: "Env Audit".into(),
            subtitle: "Compare multiple .env files or raw env blocks to find missing keys and mismatches.".into(),
            category: CommandCategory::Filesystem,
            tags: vec!["env".into(), "dotenv".into(), "compare".into(), "audit".into(), "keys".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "fs.duplicate-scan".into(),
            title: "Duplicate Scan".into(),
            subtitle: "Recursively scan a directory for duplicate files by size and SHA-256.".into(),
            category: CommandCategory::Filesystem,
            tags: vec!["duplicate".into(), "hash".into(), "files".into(), "scan".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "fs.symlink-matrix".into(),
            title: "Symlink Matrix".into(),
            subtitle: "List, inspect, create, or remove filesystem symlinks.".into(),
            category: CommandCategory::Filesystem,
            tags: vec!["symlink".into(), "link".into(), "inspect".into(), "create".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "fs.log-tail".into(),
            title: "Log Tail".into(),
            subtitle: "Read the last lines of a large local log file without opening the whole thing in the UI.".into(),
            category: CommandCategory::Filesystem,
            tags: vec!["log".into(), "tail".into(), "stream".into(), "file".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "fs.file-sentinel".into(),
            title: "File Sentinel".into(),
            subtitle: "Snapshot directories and diff later to detect created, changed, or removed files.".into(),
            category: CommandCategory::Filesystem,
            tags: vec!["watch".into(), "snapshot".into(), "diff".into(), "files".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "fs.hex-inspect".into(),
            title: "Hex Inspect".into(),
            subtitle: "Render a binary file as a structured hex and ASCII dump.".into(),
            category: CommandCategory::Filesystem,
            tags: vec!["hex".into(), "binary".into(), "inspect".into(), "dump".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "fs.batch-rename".into(),
            title: "Batch Rename".into(),
            subtitle: "Preview structured file renames using index, stem, and extension placeholders.".into(),
            category: CommandCategory::Filesystem,
            tags: vec!["rename".into(), "template".into(), "files".into(), "batch".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "fs.disk-explorer".into(),
            title: "Disk Explorer".into(),
            subtitle: "Rank the largest files and directories under a target path.".into(),
            category: CommandCategory::Filesystem,
            tags: vec!["disk".into(), "size".into(), "storage".into(), "largest".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "fs.encoding-convert".into(),
            title: "Encoding Convert".into(),
            subtitle: "Convert text between UTF-8, UTF-16 LE/BE, and ASCII.".into(),
            category: CommandCategory::Filesystem,
            tags: vec!["encoding".into(), "utf8".into(), "utf16".into(), "ascii".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "fs.archive-check".into(),
            title: "Archive Check".into(),
            subtitle: "Inspect zip, tar, and gzip archive headers for quick integrity clues.".into(),
            category: CommandCategory::Filesystem,
            tags: vec!["archive".into(), "zip".into(), "tar".into(), "gzip".into(), "integrity".into()],
            shortcut: None,
            accepts_input: true,
        },
        // ============================================================
        // Features 071-080: Frontend/UI Design Mechanics
        // ============================================================
        CommandAction {
            id: "design.eyedropper".into(),
            title: "Eyedropper".into(),
            subtitle: "Normalize sampled color values into precise hex, RGB, HSL, and Swift formats.".into(),
            category: CommandCategory::Data,
            tags: vec!["color".into(), "eyedropper".into(), "hex".into(), "rgb".into(), "hsl".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "design.color-swap".into(),
            title: "Color Swapper".into(),
            subtitle: "Convert colors across hex, RGB, HSL, CMYK, and CSS-ready outputs.".into(),
            category: CommandCategory::Data,
            tags: vec!["color".into(), "convert".into(), "cmyk".into(), "css".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "design.svg-optimize".into(),
            title: "SVG Optimize".into(),
            subtitle: "Strip comments and whitespace from SVG markup for cleaner assets.".into(),
            category: CommandCategory::Data,
            tags: vec!["svg".into(), "optimize".into(), "vector".into(), "markup".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "design.type-scale".into(),
            title: "Type Scale".into(),
            subtitle: "Translate pixel sizes into rem/em and compute modular scale steps.".into(),
            category: CommandCategory::Data,
            tags: vec!["typography".into(), "scale".into(), "rem".into(), "em".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "design.aspect-ratio".into(),
            title: "Aspect Ratio".into(),
            subtitle: "Analyze width/height pairs and generate scaled dimension references.".into(),
            category: CommandCategory::Data,
            tags: vec!["aspect".into(), "ratio".into(), "responsive".into(), "dimensions".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "design.layout-css".into(),
            title: "Layout CSS".into(),
            subtitle: "Generate flexbox or grid CSS from compact layout settings.".into(),
            category: CommandCategory::Data,
            tags: vec!["flex".into(), "grid".into(), "css".into(), "layout".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "design.mock-data".into(),
            title: "Mock Data".into(),
            subtitle: "Generate realistic-looking frontend mock records for UI prototyping.".into(),
            category: CommandCategory::Data,
            tags: vec!["mock".into(), "data".into(), "names".into(), "emails".into(), "avatars".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "design.contrast".into(),
            title: "Contrast Check".into(),
            subtitle: "Compute WCAG contrast ratios for foreground and background colors.".into(),
            category: CommandCategory::Data,
            tags: vec!["contrast".into(), "wcag".into(), "accessibility".into(), "color".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "design.shadow-gradient".into(),
            title: "Shadow/Gradient".into(),
            subtitle: "Generate copyable CSS shadows or gradients from simple parameters.".into(),
            category: CommandCategory::Data,
            tags: vec!["shadow".into(), "gradient".into(), "css".into(), "design".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "design.font-inventory".into(),
            title: "Font Inventory".into(),
            subtitle: "List installed font files discovered on the local operating system.".into(),
            category: CommandCategory::Data,
            tags: vec!["fonts".into(), "inventory".into(), "system".into(), "type".into()],
            shortcut: None,
            accepts_input: false,
        },
        // ============================================================
        // Features 081-090: Privacy-Preserving Local AI & Ollama Integration
        // ============================================================
        CommandAction {
            id: "ai.ollama-bridge".into(),
            title: "Ollama Bridge".into(),
            subtitle: "Check the local Ollama endpoint and list available models.".into(),
            category: CommandCategory::Ai,
            tags: vec!["ollama".into(), "llm".into(), "models".into(), "localhost".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "ai.error-explain".into(),
            title: "Error Explain".into(),
            subtitle: "Locally explain stack traces and common terminal/compiler failures.".into(),
            category: CommandCategory::Ai,
            tags: vec!["error".into(), "stacktrace".into(), "logs".into(), "diagnostics".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "ai.code-optimize".into(),
            title: "Code Optimize".into(),
            subtitle: "Review code locally for performance, safety, and maintainability signals.".into(),
            category: CommandCategory::Ai,
            tags: vec!["code".into(), "optimize".into(), "review".into(), "performance".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "ai.snippet-search".into(),
            title: "Snippet Search".into(),
            subtitle: "Rank candidate snippets by semantic token overlap with a query.".into(),
            category: CommandCategory::Ai,
            tags: vec!["snippet".into(), "search".into(), "semantic".into(), "retrieval".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "ai.sql-translator".into(),
            title: "SQL Translator".into(),
            subtitle: "Draft SQL queries from plain-English requests locally.".into(),
            category: CommandCategory::Ai,
            tags: vec!["sql".into(), "translate".into(), "natural language".into(), "query".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "ai.markdown-docs".into(),
            title: "Docs Drafter".into(),
            subtitle: "Generate README-style markdown scaffolding for code or packages.".into(),
            category: CommandCategory::Ai,
            tags: vec!["markdown".into(), "docs".into(), "readme".into(), "draft".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "ai.test-scaffold".into(),
            title: "Test Scaffold".into(),
            subtitle: "Produce starter unit-test templates from pasted code or signatures.".into(),
            category: CommandCategory::Ai,
            tags: vec!["tests".into(), "scaffold".into(), "unit".into(), "boilerplate".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "ai.vuln-check".into(),
            title: "Vuln Check".into(),
            subtitle: "Scan content for common exposed credentials and insecure transport patterns.".into(),
            category: CommandCategory::Ai,
            tags: vec!["security".into(), "vulnerability".into(), "secrets".into(), "scan".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "ai.rename-vars".into(),
            title: "Rename Variables".into(),
            subtitle: "Suggest clearer variable names for vague or generic identifiers.".into(),
            category: CommandCategory::Ai,
            tags: vec!["rename".into(), "variables".into(), "refactor".into(), "clarity".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "ai.offline-dict".into(),
            title: "Offline Dictionary".into(),
            subtitle: "Translate a small set of developer words and error phrases locally.".into(),
            category: CommandCategory::Ai,
            tags: vec!["dictionary".into(), "translate".into(), "offline".into(), "language".into()],
            shortcut: None,
            accepts_input: true,
        },
        // ============================================================
        // Features 091-100: Mock APIs & Testing Sandboxes
        // ============================================================
        CommandAction {
            id: "mock.http-server".into(),
            title: "HTTP Mock Server".into(),
            subtitle: "Start, stop, or inspect a local JSON mock HTTP server.".into(),
            category: CommandCategory::Network,
            tags: vec!["http".into(), "mock".into(), "server".into(), "local".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "mock.load-test".into(),
            title: "HTTP Load Test".into(),
            subtitle: "Run a basic local HTTP load profile against a target endpoint.".into(),
            category: CommandCategory::Network,
            tags: vec!["load".into(), "http".into(), "stress".into(), "benchmark".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "mock.websocket".into(),
            title: "WebSocket Lab".into(),
            subtitle: "Validate WebSocket URLs and generate raw handshake blueprints.".into(),
            category: CommandCategory::Network,
            tags: vec!["websocket".into(), "ws".into(), "socket".into(), "handshake".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "mock.graphql".into(),
            title: "GraphQL Tools".into(),
            subtitle: "Generate GraphQL introspection requests and starter query templates.".into(),
            category: CommandCategory::Network,
            tags: vec!["graphql".into(), "schema".into(), "introspection".into(), "query".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "mock.grpc".into(),
            title: "gRPC Deck".into(),
            subtitle: "Inspect pasted .proto definitions for services, RPCs, and messages.".into(),
            category: CommandCategory::Network,
            tags: vec!["grpc".into(), "proto".into(), "rpc".into(), "schema".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "mock.env-matrix".into(),
            title: "Env Mock Matrix".into(),
            subtitle: "Assemble a compact network-failure and latency simulation profile.".into(),
            category: CommandCategory::Network,
            tags: vec!["mock".into(), "latency".into(), "drop".into(), "environment".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "mock.rest-collection".into(),
            title: "REST Collection".into(),
            subtitle: "Store and retrieve local request definitions for API testing.".into(),
            category: CommandCategory::Network,
            tags: vec!["rest".into(), "collection".into(), "requests".into(), "api".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "mock.webhook".into(),
            title: "Webhook Receiver".into(),
            subtitle: "Run a local HTTP receiver and inspect captured webhook payloads.".into(),
            category: CommandCategory::Network,
            tags: vec!["webhook".into(), "receiver".into(), "logs".into(), "http".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "mock.status-codes".into(),
            title: "Status Codes".into(),
            subtitle: "Look up standard HTTP status codes and their meanings.".into(),
            category: CommandCategory::Network,
            tags: vec!["http".into(), "status".into(), "codes".into(), "reference".into()],
            shortcut: None,
            accepts_input: true,
        },
        CommandAction {
            id: "mock.cookie-parser".into(),
            title: "Cookie Parser".into(),
            subtitle: "Parse Cookie or Set-Cookie strings into readable fields and flags.".into(),
            category: CommandCategory::Network,
            tags: vec!["cookie".into(), "session".into(), "headers".into(), "parse".into()],
            shortcut: None,
            accepts_input: true,
        },
    ]
}
